---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории 1
  - Пользователь должен иметь возможность фильтровать товары 2
  - Сайт должен иметь мобильную версию 3
  - Сайт нужно протестировать на совместимость с последними версиями браузеров 4
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре 5
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины 6
  - Сайт должен быть доступен на различных устройствах 7
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы 8
  - Сайт должен быть безопасным и защищать данные пользователя 9
  - Важно, чтобы сайт мог обрабатывать большое количество трафика 10
implicit:
  - Пользователь должен иметь возможность регистрироваться в интернет-магазине 11
  - Сайт должен соблюдать политику обработки персональных данных 12
  - Сайт должен предоставлять достоверную информацию о каждом товаре (продавец, изготовление, срок службы и т.д.) 13
