---
- summary: |
    Краткое описание тест кейса. Пример: Проверка входа пользователя с существующими логином и паролем
  requirement: |
    Тестируемое требование. Например: При верном вводе логине и пароля пользователь должен войти в систему
  prerequisites: |
    Это условия, которые необходимы для проведения тест кейса. Они должны быть выполнены еще до запуска тест кейса.
    Например: открыта страница логина
  test-data: |
    Тестовые данные
    Логин = ilona Пароль = password
  steps:
    - Вводим логин
    - Вводим пароль
    - Нажимаем кнопку "Войти"
  expected-result: |
    Пользователь должен попасть на главную страницу

- summary: |
    Проверка входа пользователя с несуществующими логином и паролем
  requirement: |
    При неправильном логине или пароле пользователь должен получить сообщение об ошибке
  prerequisites:
    Открыта страница логина
  test-data: |
    Логин = Логин = hexlet Пароль = badpass
  steps:
    - Вводим логин
    - Вводим пароль
    - Нажимаем кнопку "Войти"
  expected-result: |
    Пользователь должен попасть на главную страницу

- summary: |
    Проверка возможности пользователя искать товары по ключевому слову
  requirement: |
    При существование товара в названии которого есть ключевое слово поиск должен осуществиться
  prerequisites: |
    Пользователь должен быть авторизован
    Открыта страница поиска
  test-data: |
    Пользователь вводит ключевое слово в строку поиска
    Нажимает "Поиск"
  expected-result: |
    Выгружается поиск по ключевому слову
    
- summary: |
    Поиск товаров по несущестующему ключевому слову
  requirement: |
    При отсутствии товара в названии которого есть ключевое слово поиск не должен осуществиться
  prerequisites: |
    Пользователь должен быть авторизован
    Открыта страница поиска
  test-data: |
    Пользователь вводит ключевое слово в строку поиска
    Нажимает "Поиск"
  expected-result: |
    Результат поиска отсутствует

    - summary: |
    Проверка возможности пользователя использовать фильтры
  requirement: |
    При выборе любого фильтра по нему должен осуществиться отбор товаров
  prerequisites: |
    Пользователь должен быть авторизован
  test-data: |
    Пользователь выбирает из списка категорию товаров
  expected-result: |
    Отображаются товары только выбранной категории
    
- summary: |
    Проверка отсутствия возможности отфильтровать товары по категории
  requirement: |
    При невыполнении фильтрации товаров выпадают товары из другой категории
  prerequisites: |
    Пользователь должен быть авторизован
  test-data: |
    Пользователь выбирает из списка категорию товаров
  expected-result: |
    Результат отбора по категории товара отсутствует
