---
- summary: |
    Краткое описание тест кейса. Пример: Проверка входа пользователя с существующими логином и паролем
  requirement: |
    Тестируемое требование. Например: При верном вводе логине и пароля пользователь должен войти в систему
  prerequisites: |
    Это условия, которые необходимы для проведения тест кейса. Они должны быть выполнены еще до запуска тест кейса.
    Например: открыта страница логина
  test-data: |
    Тестовые данные
    Логин = ilona Пароль = password
  steps:
    - Вводим логин
    - Вводим пароль
    - Нажимаем кнопку "Войти"
  expected-result: |
    Пользователь должен попасть на главную страницу

- summary: |
    Проверка входа пользователя с несуществующими логином и паролем
  requirement: |
    При неправильном логине или пароле пользователь должен получить сообщение об ошибке
  prerequisites:
    Открыта страница логина
  test-data: |
    Логин = Логин = hexlet Пароль = badpass
  steps:
    - Вводим логин
    - Вводим пароль
    - Нажимаем кнопку "Войти"
  expected-result: |
    Пользователь должен попасть на главную страницу

- summary: |
    Проверка возможности пользователя искать товары по ключевому слову
  requirement: |
    При существование товара в названии которого есть ключевое слово поиск должен осуществиться
  prerequisites: |
    Пользователь должен быть авторизован
    Открыта страница поиска
  test-data: |
    Пользователь вводит ключевое слово в строку поиска
    Нажимает "Поиск"
  expected-result: |
    Выгружается поиск по ключевому слову
    
- summary: |
    Поиск товаров по несущестующему ключевому слову
  requirement: |
    При отсутствии товара в названии которого есть ключевое слово поиск не должен осуществиться
  prerequisites: |
    Пользователь должен быть авторизован
    Открыта страница поиска
  test-data: |
    Пользователь вводит ключевое слово в строку поиска
    Нажимает "Поиск"
  expected-result: |
    Результат поиска отсутствует

    - summary: |
    Проверка возможности пользователя использовать фильтры
  requirement: |
    При выборе любого фильтра по нему должен осуществиться отбор товаров
  prerequisites: |
    Пользователь должен быть авторизован
  test-data: |
    Пользователь выбирает из списка категорию товаров
  expected-result: |
    Отображаются товары только выбранной категории
    
- summary: |
    Проверка отсутствия возможности отфильтровать товары по категории
  requirement: |
    При невыполнении фильтрации товаров выпадают товары из другой категории
  prerequisites: |
    Пользователь должен быть авторизован
  test-data: |
    Пользователь выбирает из списка категорию товаров
  expected-result: |
    Результат отбора по категории товара отсутствует

    - summary: |
    Проверка наличия мобильной версии сайта
  requirement: |
    При выполнении входа в магазин с мобильного устройства дизайн страницы адаптируется под экран пользователя
  prerequisites: |
    Пользователь должен быть авторизован
  test-data: |
    Пользователь заходит в магазин через мобильное устройство
  expected-result: |
    Дизайн страницы адаптируется под экран пользователя, все необходимые разделы и кнопки присутствуют
    
- summary: |
    Проверка отсутствия мобильной версии сайта
  requirement: |
    При выполнении входа в магазин с мобильного устройства дизайн страницы не адаптируется под экран пользователя
  prerequisites: |
    Пользователь должен быть авторизован
  test-data: |
    Пользователь заходит в магазин через мобильное устройство
  expected-result: |
    Дизайн страницы не адаптируется под экран пользователя, разделы не читаемы, кнопки отсутствуют

- summary: |
    Проверка на совместимость с последними версиями браузеров
  requirement: |
    При выполнении входа в магазин с различных браузеров (Google Chrome, Mozilla Firefox, Safari, Opera) убедиться, 
    что магазин выглядит и работает одинаково на всех браузерах, без каких-либо отклонений и ошибок в отображении или функциональности
  prerequisites: |
    Пользователь должен быть авторизован
  test-data: |
    Пользователь заходит в магазин через браузеры Google Chrome, Mozilla Firefox, Safari, Opera
  expected-result: |
    Магазин выглядит и работает одинаково на всех браузерах, без каких-либо отклонений и ошибок в отображении или функциональности
    
- summary: |
    Проверка на отсутсвие совместимости с последними версиями браузеров
  requirement: |
    При выполнении входа в магазин с различных браузеров (Google Chrome, Mozilla Firefox, Safari, Opera) убедиться, 
    что магазин выглядит и работает не одинаково на всех браузерах, с какими-либо отклонениями и ошибками в отображении или функциональности
  prerequisites: |
    Пользователь должен быть авторизован
  test-data: |
    Пользователь заходит в магазин через браузеры Google Chrome, Mozilla Firefox, Safari, Opera
  expected-result: |
    Отсутствует возможность фильтровать товары в браузере Opera

- summary: |
    Проверка возможности пользователя просматривать товары и просматривать подробную информацию о товаре
  requirement: |
    При выборе любого товара - должна отображаться подробная информация о товаре
  prerequisites: |
    Пользователь должен быть авторизован
  test-data: |
    Пользователь выбирает любой товар из магазина
  expected-result: |
    Отображаются изображение, название, описание товара, его рейтинг и стоимость, а также количество заказов
    
- summary: |
    Проверка возможности пользователя просматривать товары и просматривать подробную информацию о товаре
  requirement: |
    При выборе любого товара - не отображается полная информация о товаре
  prerequisites: |
    Пользователь должен быть авторизован
  test-data: |
    Пользователь выбирает любой товар из магазина
  expected-result: |
    Отображаются название, описание товара, его рейтинг и стоимость, но отсутствует количество заказов

- summary: |
    Проверка возможности пользователя добавлять товары в корзину
  requirement: |
    При нажатии внизу товара кнопки "В корзину" - товар должен появиться в корзине
  prerequisites: |
    Пользователь должен быть авторизован
  test-data: |
    Пользователь выбирает любой товар из магазина и нажимает на кнопку "В корзину"
    Пользователь переходит в корзину
  expected-result: |
    Выбранный товар отображается в корзине

  - summary: |
    Проверка отсутствия возможности пользователю добавлять товары в корзину
  requirement: |
    При нажатии внизу товара кнопки "В корзину" - товар не появляется в корзине
  prerequisites: |
    Пользователь должен быть авторизован
  test-data: |
    Пользователь выбирает любой товар из магазина и нажимает на кнопку "В корзину"
    Пользователь переходит в корзину
  expected-result: |
    Выбранный товар не отображается в корзине  

    
